<?php
/**
 * Extended registration form
 * 
 * @author     Design:Slider GbR <magento@design-slider.de>
 * @copyright  (C)Design:Slider GbR <www.design-slider.de>
 * @license    OSL <http://opensource.org/licenses/osl-3.0.php>
 * @link       http://www.design-slider.de/magento_onlineshop/magento-extensions/registration-address/
 * @package    DS_RegAddress
 * @version    CE 1.7
 */

$requiredClass = $this->getAddressForced() ? 'required' : '';
$requiredCharacter = $this->getAddressForced() ? '*' : '';
?>
<div class="account-create">
    <div class="page-title">
        <h1><?php echo $this->__('Create an Account') ?></h1>
    </div>
    <?php echo $this->getChildHtml('form_fields_before')?>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php /* Extensions placeholder */ ?>
    <?php echo $this->getChildHtml('customer.form.register.extra')?>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate">
        <div class="fieldset">
            <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
            <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
            <h2 class="legend"><?php echo $this->__('Personal Information') ?></h2>
            <ul class="form-list">
                <li class="fields">
                    <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
                </li>
                <li>
                    <label for="email_address" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                    <div class="input-box">
                        <input type="text" name="email" id="email_address" value="<?php echo $this->escapeHtml($this->getFormData()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
                    </div>
                </li>
                <li>
                    <label for="email_address_cc"><?php echo $this->__('Email Address CC') ?></label>
                    <div class="input-box">
                        <input type="text" name="email_cc" id="email_cc" value="<?php echo $this->escapeHtml($this->getFormData()->getEmailCc()) ?>" title="<?php echo $this->__('Email CC') ?>" class="input-text validate-email" />
                    </div>
                </li>
                <?php if ($this->isNewsletterEnabled()): ?>
                <li class="control">
                    <div class="input-box">
                        <input type="checkbox" name="is_subscribed" title="<?php echo $this->__('Sign Up for Newsletter') ?>" value="1" id="is_subscribed"<?php if($this->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox" />
                    </div>
                    <label for="is_subscribed"><?php echo $this->__('Sign Up for Newsletter') ?></label>
                    <?php /* Extensions placeholder */ ?>
                    <?php echo $this->getChildHtml('customer.form.register.newsletter')?>
                </li>
                <?php endif ?>
            <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
            <?php if ($_dob->isEnabled()): ?>
                <li><?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml() ?></li>
            <?php endif ?>
            <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
            <?php if ($_taxvat->isEnabled()): ?>
                <li><?php echo $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?></li>
            <?php endif ?>
            <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
            <?php if ($_gender->isEnabled()): ?>
                <li><?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() ?></li>
            <?php endif ?>
            </ul>
        </div>
    <?php if($this->getShowAddressFields()): ?>
        <div class="fieldset">
            <input id="create_address" type="hidden" name="create_address" value="1" />
            <h2 class="legend"><?php echo $this->__('Address Information') ?></h2>
            <ul class="form-list">
                <li class="fields">
                    <div class="field">
                        <label for="country" class="<?php echo $requiredClass ?>"><em><?php echo $requiredCharacter ?></em><?php echo $this->__('Country') ?></label>
                        <div class="input-box">
                            <?php echo $this->getCountryHtmlSelect() ?>
                        </div>
                    </div>
                    <div class="field">
                        <label for="region_id" class="<?php echo $requiredClass ?>"><em><?php echo $requiredCharacter ?></em><?php echo $this->__('State/Province') ?></label>
                        <div class="input-box">
                            <select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
                                <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                            </select>
                            <script type="text/javascript">
                            //<![CDATA[
                                $('region_id').setAttribute('defaultValue', "<?php echo $this->getFormData()->getRegionId() ?>");
                            //]]>
                            </script>
                            <input type="text" id="region" name="region" value="<?php echo $this->escapeHtml($this->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="city" class="<?php echo $requiredClass ?>"><em><?php echo $requiredCharacter ?></em><?php echo $this->__('City') ?></label>
                        <div class="input-box">
                            <input type="text" id="city" name="city" value="<?php echo $this->escapeHtml($this->getFormData()->getCity()) ?>" title="<?php echo $this->__('City') ?>" class="input-text create-address-indicator <?php echo $this->getAddressForced() ? $this->helper('customer/address')->getAttributeValidationClass('city') : '' ?>" id="city" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="kecamatan" class="<?php echo $requiredClass ?>"><em><?php echo $requiredCharacter ?></em><?php echo $this->__('Kecamatan') ?></label>
                        <div class="input-box">
                            <input type="text" id="kecamatan" name="kecamatan" value="<?php echo $this->escapeHtml($this->getFormData()->getKecamatan()) ?>" title="<?php echo $this->__('Kecamatan') ?>" class="input-text create-address-indicator <?php echo $this->getAddressForced() ? $this->helper('customer/address')->getAttributeValidationClass('kecamatan') : '' ?>" id="kecamatan" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="kelurahan" class="<?php echo $requiredClass ?>"><em><?php echo $requiredCharacter ?></em><?php echo $this->__('Kelurahan') ?></label>
                        <div class="input-box">
                            <input type="text" id="kelurahan" name="kelurahan" value="<?php echo $this->escapeHtml($this->getFormData()->getKelurahan()) ?>" title="<?php echo $this->__('Kelurahan') ?>" class="input-text create-address-indicator <?php echo $this->getAddressForced() ? $this->helper('customer/address')->getAttributeValidationClass('kelurahan') : '' ?>" id="kelurahan" />
                        </div>
                    </div>                 
                </li>
                <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                <li class="wide">
                    <label for="street_1" class="<?php echo $requiredClass ?>"><em><?php echo $requiredCharacter ?></em><?php echo $this->__('Street Address') ?></label>
                    <div class="input-box">
                        <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet(1)) ?>" title="<?php echo $this->__('Street Address') ?>" id="street_1" class="input-text create-address-indicator <?php echo $this->getAddressForced() ? $_streetValidationClass : ''?>" />
                    </div>
                </li>
            <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
            <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                <li class="wide">
                    <div class="input-box">
                        <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet($_i)) ?>" title="<?php echo $this->__('Street Address %s', $_i) ?>" id="street_<?php echo $_i ?>" class="input-text <?php echo $this->getAddressForced() ? $_streetValidationClass : '' ?>" />
                    </div>
                </li>
            <?php endfor; ?>
                
                <li class="fields">
                    
                    <?php if (!$this->getAddressForced()): ?>
                    <div class="field">
                        <label for="zip" class="<?php echo $requiredClass ?>"><em><?php echo $requiredCharacter ?></em><?php echo $this->__('Zip/Postal Code') ?></label>
                        <div class="input-box">
                            <input type="text" id="postcode" name="postcode" value="<?php echo $this->escapeHtml($this->getFormData()->getPostcode()) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international create-address-indicator <?php echo $this->getAddressForced() ? $this->helper('customer/address')->getAttributeValidationClass('postcode') : ''?>" />
                        </div>
                    </div>
                    <?php else: ?>
                    <div class="field">
                        <label for="zip" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
                        <div class="input-box">
                            <input type="text" name="postcode" value="<?php echo $this->escapeHtml($this->getFormData()->getPostcode()) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
                        </div>
                    </div>
                    <?php endif; ?>                    
                </li>
                <li class="fields">
                    <div class="field">
                        <label for="company"><?php echo $this->__('Outlet Name') ?></label>
                        <div class="input-box">
                            <input type="text" name="company" id="company" value="<?php echo $this->escapeHtml($this->getFormData()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" />
                        </div>
                    </div>
                    <?php
                    $model = Mage::getModel('multistockpoint/eav_entity_attribute_source_customeroptionsoutletype');
                    $rows = $model->getAllOptions();
                    if($rows[0]['visibility'] != 0):
                    ?>
                    <div class="field">
                        <label for="outlet_type"><?php echo $this->__('Outlet Type') ?></label>
                        <div class="input-box">
                             <select name="outlet_type" id="outlet_type">
                                <?php
                                foreach($rows as $type){
                                    ?>
                                    <option value="<?php echo $type['value']?>"><?php echo $type['value'];?></option>
                                    <?php
                                }?>
                            </select>
                            </div>
                    </div>
                    <?php
                    endif;
                    ?>
                    <div class="field">
                        <label for="outlet_owner"><?php echo $this->__('Outlet Owner') ?></label>
                        <div class="input-box">
                            <input type="text" name="outlet_owner" id="outlet_owner" value="<?php echo $this->escapeHtml($this->getFormData()->getOutletOwner()) ?>" title="<?php echo $this->__('Outlet Owner') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('outlet_owner') ?>" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="ktp_number"><?php echo $this->__('ID Number') ?></label>
                        <div class="input-box">
                            <input type="text" name="ktp_number" id="ktp_number" value="<?php echo $this->escapeHtml($this->getFormData()->getKtpNumber()) ?>" title="<?php echo $this->__('ID Card') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('ktp_number') ?>" />
                        </div>
                    </div>
                    <?php
                    $model = Mage::getModel('multistockpoint/eav_entity_attribute_source_customeroptionsnpwp');
                    $rows = $model->getAllOptions();
                    if($rows[0]['visibility'] != 0):
                    ?>
                    <div class="field">
                        <label for="npwp_type"><?php echo $this->__('NPWP Type') ?></label>
                        <div class="input-box">
                            <select name="npwp_type" id="npwp_type">
                                <?php                                
                                foreach($rows as $type){
                                    ?>
                                    <option value="<?php echo $type['value']?>"><?php echo $type['value']?></option>
                                    <?php
                                }
                                ?>
                            </select>
                        </div>
                    </div>
                    <?php
                    endif;
                    ?>
                    <div class="field">
                        <label for="npwp_number"><?php echo $this->__('NPWP Number') ?></label>
                        <div class="input-box">
                            <input type="text" name="npwp_number" id="npwp_number" value="<?php echo $this->escapeHtml($this->getFormData()->getNpwpNumber()) ?>" title="<?php echo $this->__('NPWP Number') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('npwp_number') ?>" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="npwp_name"><?php echo $this->__('NPWP Name') ?></label>
                        <div class="input-box">
                            <input type="text" name="npwp_name" id="npwp_name" value="<?php echo $this->escapeHtml($this->getFormData()->getNpwpName()) ?>" title="<?php echo $this->__('NPWP Name') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('npwp_name') ?>" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="npwp_address"><?php echo $this->__('NPWP Address') ?></label>
                        <div class="input-box">
                            <input type="text" name="npwp_address" id="npwp_address" value="<?php echo $this->escapeHtml($this->getFormData()->getNpwpAddress()) ?>" title="<?php echo $this->__('NPWP Address') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('npwp_address') ?>" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="telephone" class="<?php echo $requiredClass ?>"><em><?php echo $requiredCharacter ?></em><?php echo $this->__('Telephone') ?></label>
                        <div class="input-box">
                            <input type="text" name="telephone" id="telephone" value="<?php echo $this->escapeHtml($this->getFormData()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text <?php echo $this->getAddressForced() ? $this->helper('customer/address')->getAttributeValidationClass('telephone') : ''?>" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="mobile_number" class="<?php echo $requiredClass ?>"><em><?php echo $requiredCharacter ?></em><?php echo $this->__('Mobile Number') ?></label>
                        <div class="input-box">
                            <input type="text" name="mobile_number" id="mobile_number" value="<?php echo $this->escapeHtml($this->getFormData()->getMobileNumber()) ?>" title="<?php echo $this->__('Mobile Number') ?>" class="input-text <?php echo $this->getAddressForced() ? $this->helper('customer/address')->getAttributeValidationClass('mobile_number') : ''?>" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="fax" class="<?php echo $requiredClass ?>"><em><?php echo $requiredCharacter ?></em><?php echo $this->__('Fax') ?></label>
                        <div class="input-box">
                            <input type="text" name="fax" id="fax" value="<?php echo $this->escapeHtml($this->getFormData()->getFax()) ?>" title="<?php echo $this->__('Fax') ?>" class="input-text <?php echo $this->getAddressForced() ? $this->helper('customer/address')->getAttributeValidationClass('fax') : ''?>" />
                        </div>
                    </div>
                </li>
            
            </ul>
            <input type="hidden" name="default_billing" value="1" />
            <input type="hidden" name="default_shipping" value="1" />
        </div>
    <?php endif; ?>
        <div class="fieldset">
            <h2 class="legend"><?php echo $this->__('Login Information') ?></h2>
            <ul class="form-list">
                <li class="fields">
                    <div class="field">
                        <label for="password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                        <div class="input-box">
                            <input type="password" name="password" id="password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm Password') ?></label>
                        <div class="input-box">
                            <input type="password" name="confirmation" title="<?php echo $this->__('Confirm Password') ?>" id="confirmation" class="input-text required-entry validate-cpassword" />
                        </div>
                    </div>
                </li>
                <?php echo $this->getChildHtml('form.additional.info'); ?>
            </ul>
        </div>
        <div class="buttons-set">
            <p class="required"><?php echo $this->__('* Required Fields') ?></p>
            <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>" class="back-link"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
            <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
        <?php if($this->getShowAddressFields()): ?>
        var _regionConfig = <?php echo $this->helper('directory')->getRegionJson(); ?>;

            <?php if (!$this->getAddressForced()): ?>
                _regionConfig.config.regions_required = [];
            <?php endif; ?>
        
        var ru = new RegionUpdater('country', 'region', 'region_id', _regionConfig, undefined, 'zip');
        <?php endif; ?>

        <?php if($this->getShowAddressFields() && !$this->getAddressForced()): ?>
        Event.observe(window, 'load', function() {
            initMamokuRegAddress();
        });

        function initMamokuRegAddress() {
            updateCreateAddress();
            $$('.create-address-indicator').each(function(e) {
                $(e.id).on('change', function() {
                    updateCreateAddress();
                });
            });
        }

        function updateCreateAddress(){
            if ($('postcode').value == '' && $('street_1').value == '' && $('city').value == ''
                 && $('kecamatan').value == '' && $('kelurahan').value == '') {
                $('create_address').value = 0;
            } else {
                $('create_address').value = 1;
            }
        }
        <?php endif; //eof getShowAddressFields && !$this->getAddressForced() ?>
        
    //]]>
    </script>
</div>